#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "${SCRIPT_DIR}")"
OUTPUT="${SCRIPT_DIR}/generated/soomgil_demo_dashboard_dump.sql"

base_source="${SCRIPT_DIR}/soomgil_demo_seoul_daejeon.sql"
legacy_sources=(
  "${BACKEND_DIR}/dev-seeds/98_enable_timestamp_defaults.sql"
  "${BACKEND_DIR}/dev-seeds/01_auth.sql"
  "${BACKEND_DIR}/dev-seeds/02_social_media.sql"
  "${BACKEND_DIR}/dev-seeds/03_geo.sql"
  "${BACKEND_DIR}/dev-seeds/04_trips_members.sql"
  "${BACKEND_DIR}/dev-seeds/05_itinerary.sql"
  "${BACKEND_DIR}/dev-seeds/06_planning_chat.sql"
  "${BACKEND_DIR}/dev-seeds/08_ai.sql"
  "${BACKEND_DIR}/dev-seeds/09_record.sql"
  "${BACKEND_DIR}/dev-seeds/10_community.sql"
  "${BACKEND_DIR}/dev-seeds/11_notification_collab_ops.sql"
  "${BACKEND_DIR}/dev-seeds/12_local_user_enrichment.sql"
  "${BACKEND_DIR}/dev-seeds/99_disable_timestamp_defaults.sql"
)
patch_sources=(
  "${SCRIPT_DIR}/soomgil_demo_realistic_patch.sql"
  "${SCRIPT_DIR}/soomgil_demo_kto_places.sql"
)

mkdir -p "$(dirname "${OUTPUT}")"
{
  printf '%s\n' '-- Generated by seeds/build_demo_dashboard_dump.sh. Do not edit directly.'
  printf '%s\n\n' '\set ON_ERROR_STOP on'
  for source in "${base_source}"; do
    printf '\n-- BEGIN %s\n\n' "${source#"${BACKEND_DIR}/"}"
    sed '/^\\set ON_ERROR_STOP on$/d' "${source}"
    printf '\n-- END %s\n' "${source#"${BACKEND_DIR}/"}"
  done

  printf '%s\n' "SELECT NOT EXISTS (SELECT 1 FROM trip.trips WHERE id = 'c0000000-0000-4000-8000-000000000001') AS load_legacy_demo \\gset"
  printf '%s\n' '\if :load_legacy_demo'
  for source in "${legacy_sources[@]}"; do
    printf '\n-- BEGIN %s\n\n' "${source#"${BACKEND_DIR}/"}"
    sed '/^\\set ON_ERROR_STOP on$/d' "${source}"
    printf '\n-- END %s\n' "${source#"${BACKEND_DIR}/"}"
  done
  printf '%s\n' '\endif'

  for source in "${patch_sources[@]}"; do
    printf '\n-- BEGIN %s\n\n' "${source#"${BACKEND_DIR}/"}"
    sed '/^\\set ON_ERROR_STOP on$/d' "${source}"
    printf '\n-- END %s\n' "${source#"${BACKEND_DIR}/"}"
  done
} > "${OUTPUT}"

echo "Generated ${OUTPUT}"
