#!/usr/bin/env bash
# 생성기가 만든 라이브 DB에서 앱 데이터만 덤프해 generated/soomgil_demo_dashboard_dump.sql 로 굳힌다.
# 참조 데이터(관광지·법정동·태그 사전/enrichment·온보딩 설문)는 Flyway가 넣으므로 제외한다.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${SCRIPT_DIR}/../generated/soomgil_demo_dashboard_dump.sql"
CID="$(docker compose -f "${SCRIPT_DIR}/../../../compose.yaml" ps -q postgres)"
DB_USER="${DB_USERNAME:-soomgil}"; DB_NAME="${DB_NAME:-soomgil}"
[ -n "$CID" ] || { echo "postgres container not running" >&2; exit 1; }
mkdir -p "$(dirname "$OUT")"
{
  echo '-- Generated by seeds/v2/build_dump_v2.sh from the live demo DB. Do not edit by hand.'
  echo '-- Apply on an empty database after Flyway migrations (node init-demo-dump.mjs).'
  echo '\set ON_ERROR_STOP on'
  echo 'SET session_replication_role = replica;'
  docker exec -i "$CID" pg_dump -U "$DB_USER" -d "$DB_NAME" --data-only --column-inserts --rows-per-insert=200 --no-owner --no-privileges \
    -n auth -n social -n trip -n itinerary -n planning -n chat -n community -n media -n voting -n notification -n ai -n preference -n collab -n ops \
    -T 'preference.preference_tags' -T 'preference.place_tag_enrichments' -T 'preference.place_tag_enrichment_tags' -T 'preference.place_tag_enrichment_candidates' \
    -T 'preference.tag_statistic_runs' -T 'preference.tag_statistics' -T 'preference.synthetic_*' -T 'preference.onboarding_survey_versions' -T 'preference.onboarding_survey_places' \
    -T 'auth.roles' -T 'auth.auth_providers' -T 'auth.policy_documents' -T 'community.report_reasons' -T 'auth.user_sessions' -T 'auth.user_security_events' -T 'media.upload_intents' \
    | grep -vE '^(SET |SELECT pg_catalog\.set_config|\\restrict|\\unrestrict|--$)'
  echo 'SET session_replication_role = DEFAULT;'
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"
