CREATE SCHEMA IF NOT EXISTS tourism_source;

CREATE TABLE tourism_source.contenttypes (
	content_type_id integer PRIMARY KEY,
	content_type_name varchar(100) NOT NULL
);

CREATE TABLE tourism_source.attractions (
	no integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	content_id integer NOT NULL UNIQUE,
	title varchar(500) NOT NULL,
	content_type_id integer,
	area_code integer,
	si_gun_gu_code integer,
	first_image1 text,
	first_image2 text,
	map_level integer,
	latitude double precision,
	longitude double precision,
	tel varchar(80),
	addr1 varchar(300),
	addr2 varchar(300),
	homepage text,
	overview text,
	source_hash varchar(128),
	source_modified_at timestamp with time zone,
	imported_at timestamp with time zone NOT NULL DEFAULT now(),
	CONSTRAINT fk_attractions_content_type
		FOREIGN KEY (content_type_id)
		REFERENCES tourism_source.contenttypes (content_type_id)
);

CREATE TABLE tourism_source.attraction_images (
	id uuid PRIMARY KEY,
	attraction_no integer NOT NULL,
	source_provider varchar(80) NOT NULL DEFAULT 'KTO',
	source_type varchar(40) NOT NULL,
	original_url text,
	storage_provider varchar(40),
	bucket varchar(120),
	object_key text,
	public_url text NOT NULL,
	display_order integer NOT NULL DEFAULT 999,
	width integer,
	height integer,
	checksum_sha256 varchar(128),
	is_active boolean NOT NULL DEFAULT true,
	created_at timestamp with time zone NOT NULL DEFAULT now(),
	updated_at timestamp with time zone NOT NULL DEFAULT now(),
	CONSTRAINT fk_attraction_images_attraction
		FOREIGN KEY (attraction_no)
		REFERENCES tourism_source.attractions (no)
		ON DELETE CASCADE
);

CREATE INDEX idx_attractions_title
	ON tourism_source.attractions (title);

CREATE INDEX idx_attractions_content_type
	ON tourism_source.attractions (content_type_id);

CREATE INDEX idx_attractions_region
	ON tourism_source.attractions (area_code, si_gun_gu_code);

CREATE INDEX idx_attractions_location
	ON tourism_source.attractions (longitude, latitude);

CREATE INDEX idx_attraction_images_display
	ON tourism_source.attraction_images (attraction_no, is_active, display_order, created_at);
